version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: [ "php" ]
  composer:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
      - ./composer:/root/.composer
    entrypoint: [ "composer" ]